# Generated by Django 5.2.1 on 2025-05-16 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Tiêu đề")),
                ("message", models.TextField(verbose_name="Nội dung")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Thông tin"),
                            ("success", "Thành công"),
                            ("warning", "Cảnh báo"),
                            ("error", "Lỗi"),
                            ("request", "Yêu cầu"),
                            ("approval", "Phê duyệt"),
                            ("system", "Hệ thống"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Loại thông báo",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                ("is_sent", models.BooleanField(default=False, verbose_name="Đã gửi")),
                (
                    "is_email_sent",
                    models.BooleanField(default=False, verbose_name="Đã gửi email"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID đối tượng",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dữ liệu bổ sung"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="URL liên kết",
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Chữ hiển thị trên nút hành động",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm đọc"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm gửi"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Loại đối tượng",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient"], name="notificatio_recipie_be3f1a_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_9edb86_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="notificatio_content_702c56_idx",
                    ),
                ],
            },
        ),
    ]
