# Generated by Django 5.1.7 on 2025-03-17 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('request_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('death_certificate', 'Death Certificate'), ('marriage_certificate', 'Marriage Certificate'), ('building_permit', 'Building Permit'), ('business_license', 'Business License'), ('land_registration', 'Land Registration'), ('tax_clearance', 'Tax Clearance'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Chairman Review'), ('ASSIGNED', 'Assigned to Officer'), ('IN_PROGRESS', 'In Progress'), ('ADDITIONAL_INFO', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('user_hash', models.CharField(max_length=66, unique=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'Pending Chairman Review'), ('ASSIGNED', 'Assigned to Officer'), ('IN_PROGRESS', 'In Progress'), ('ADDITIONAL_INFO', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending Chairman Review'), ('ASSIGNED', 'Assigned to Officer'), ('IN_PROGRESS', 'In Progress'), ('ADDITIONAL_INFO', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='blockchain.administrativerequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
