# Generated by Django 5.1.7 on 2025-03-23 16:40

import blockchain.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeststatusupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='administrativerequest',
            name='payment_transaction_hash',
        ),
        migrations.AddField(
            model_name='administrativerequest',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativerequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='request_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('RESIDENCE_CERT', 'Residence Certificate'), ('MARRIAGE_CERT', 'Marriage Certificate'), ('BUS_PERMIT', 'Business Permit'), ('LAND_TITLE', 'Land Title'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ADDITIONAL_INFO', 'Additional Information Needed'), ('APPROVED', 'Approved'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requeststatusupdate',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ADDITIONAL_INFO', 'Additional Information Needed'), ('APPROVED', 'Approved'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststatusupdate',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ADDITIONAL_INFO', 'Additional Information Needed'), ('APPROVED', 'Approved'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststatusupdate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='blockchain.administrativerequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SUBMISSION', 'Initial Submission'), ('SUPPORTING_DOC', 'Supporting Document'), ('ADDITIONAL_INFO', 'Additional Information'), ('OFFICIAL_RESPONSE', 'Official Response'), ('CERTIFICATE', 'Certificate'), ('PERMIT', 'Permit'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to=blockchain.models.get_document_upload_path)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='If checked, the document is visible to all parties involved with this request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blockchain.administrativerequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
