# Generated by Django 5.0.2 on 2025-04-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_requeststatusupdate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativerequest',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data storing form fields specific to this request type'),
        ),
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_fields', models.JSONField(blank=True, default=dict, help_text='JSON defining required fields for this category')),
                ('form_template', models.JSONField(blank=True, default=dict, help_text='JSON template for form structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officials', models.ManyToManyField(blank=True, limit_choices_to={'profile__approval_status': 'APPROVED', 'profile__role': 'OFFICIAL'}, related_name='assigned_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Category',
                'verbose_name_plural': 'Request Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='administrativerequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='blockchain.requestcategory'),
        ),
    ]
