# Generated by Django 5.2.1 on 2025-05-16 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã phản hồi",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("suggestion", "Góp ý"),
                            ("complaint", "Phàn nàn"),
                            ("question", "Câu hỏi"),
                            ("bug_report", "Báo lỗi"),
                            ("other", "Khác"),
                        ],
                        default="suggestion",
                        max_length=20,
                        verbose_name="Loại phản hồi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ xử lý"),
                            ("in_progress", "Đang xử lý"),
                            ("resolved", "Đã giải quyết"),
                            ("closed", "Đã đóng"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, null=True, verbose_name="Phản hồi"),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày phản hồi"
                    ),
                ),
                (
                    "is_satisfied",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Hài lòng với phản hồi"
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Đánh giá (1-5)"
                    ),
                ),
                (
                    "satisfaction_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nhận xét thêm"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Công khai"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Ẩn danh"),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xử lý",
                    ),
                ),
                (
                    "related_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="administrative.document",
                        verbose_name="Giấy tờ liên quan",
                    ),
                ),
                (
                    "related_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="administrative.request",
                        verbose_name="Yêu cầu liên quan",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phản hồi",
                "verbose_name_plural": "Phản hồi",
                "ordering": ["-created_at", "status"],
                "indexes": [
                    models.Index(
                        fields=["feedback_id"], name="feedback_fe_feedbac_b2f0d8_idx"
                    ),
                    models.Index(
                        fields=["submitter"], name="feedback_fe_submitt_34dc49_idx"
                    ),
                    models.Index(
                        fields=["handler"], name="feedback_fe_handler_cfbe37_idx"
                    ),
                    models.Index(
                        fields=["status"], name="feedback_fe_status_35d074_idx"
                    ),
                    models.Index(
                        fields=["feedback_type"], name="feedback_fe_feedbac_ba1d78_idx"
                    ),
                ],
            },
        ),
    ]
