# Generated by Django 5.2.1 on 2025-05-16 13:37

import apps.administrative.models.attachment
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên loại giấy tờ"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã giấy tờ"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "requires_officer_approval",
                    models.BooleanField(
                        default=True, verbose_name="Yêu cầu cán bộ xã phê duyệt"
                    ),
                ),
                (
                    "requires_chairman_approval",
                    models.BooleanField(
                        default=False, verbose_name="Yêu cầu chủ tịch phê duyệt"
                    ),
                ),
                (
                    "estimated_processing_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Thời gian xử lý dự kiến (ngày)"
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("simple", "Đơn giản"),
                            ("medium", "Trung bình"),
                            ("complex", "Phức tạp"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Độ phức tạp",
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Các trường dữ liệu bắt buộc",
                    ),
                ),
                (
                    "optional_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Các trường dữ liệu tùy chọn",
                    ),
                ),
                (
                    "required_attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Các tài liệu đính kèm bắt buộc",
                    ),
                ),
                (
                    "optional_attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Các tài liệu đính kèm không bắt buộc",
                    ),
                ),
                (
                    "store_on_blockchain",
                    models.BooleanField(
                        default=True, verbose_name="Lưu trữ trên blockchain"
                    ),
                ),
                (
                    "blockchain_contract",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Smart contract",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Phí xử lý (VND)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loại giấy tờ",
                "verbose_name_plural": "Loại giấy tờ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã yêu cầu",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số tham chiếu"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("submitted", "Đã nộp"),
                            ("in_review", "Đang xem xét"),
                            ("additional_info_required", "Yêu cầu bổ sung thông tin"),
                            ("approved", "Đã phê duyệt"),
                            ("rejected", "Từ chối"),
                            ("processing", "Đang xử lý"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("normal", "Bình thường"),
                            ("high", "Cao"),
                            ("urgent", "Khẩn cấp"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Mức độ ưu tiên",
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày nộp"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày phê duyệt"
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày hoàn thành"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày đến hạn"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do từ chối"
                    ),
                ),
                (
                    "additional_info_request",
                    models.TextField(
                        blank=True, null=True, verbose_name="Yêu cầu bổ sung thông tin"
                    ),
                ),
                (
                    "additional_info_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phản hồi bổ sung"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Dữ liệu"),
                ),
                (
                    "is_recorded_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Đã ghi blockchain"
                    ),
                ),
                (
                    "blockchain_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blockchain_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phê duyệt",
                    ),
                ),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cán bộ xử lý",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="administrative.documenttype",
                        verbose_name="Loại giấy tờ",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người yêu cầu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu",
                "verbose_name_plural": "Yêu cầu",
                "ordering": ["-created_at", "status"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã giấy tờ",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số tham chiếu"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("issued", "Đã ban hành"),
                            ("revoked", "Thu hồi"),
                            ("expired", "Hết hạn"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "is_verified_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Đã xác thực blockchain"
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày cấp"),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Có hiệu lực từ"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Có hiệu lực đến"
                    ),
                ),
                (
                    "blockchain_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                (
                    "blockchain_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Địa chỉ blockchain",
                    ),
                ),
                (
                    "verification_hash",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mã băm xác thực",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Mã QR",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Dữ liệu"),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="File giấy tờ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("blockchain_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người cấp",
                    ),
                ),
                (
                    "issued_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhận",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="administrative.documenttype",
                        verbose_name="Loại giấy tờ",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_documents",
                        to="administrative.request",
                        verbose_name="Yêu cầu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giấy tờ",
                "verbose_name_plural": "Giấy tờ",
                "ordering": ["-issued_date", "reference_number"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã tài liệu",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên tài liệu")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("identity_card", "Căn cước công dân/CMND"),
                            ("birth_certificate", "Giấy khai sinh"),
                            ("household_registration", "Sổ hộ khẩu"),
                            ("marriage_certificate", "Giấy chứng nhận kết hôn"),
                            ("property_certificate", "Giấy chứng nhận quyền sở hữu"),
                            ("tax_document", "Tài liệu thuế"),
                            ("business_registration", "Giấy đăng ký kinh doanh"),
                            ("qualification", "Văn bằng/Chứng chỉ"),
                            ("supporting_document", "Tài liệu hỗ trợ"),
                            ("application_form", "Đơn đăng ký"),
                            ("photo", "Ảnh"),
                            ("other", "Khác"),
                        ],
                        max_length=30,
                        verbose_name="Loại tài liệu",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.administrative.models.attachment.attachment_file_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kích thước (bytes)"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Loại file"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Đã xác thực"),
                ),
                (
                    "verification_hash",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mã băm xác thực",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày xác thực"
                    ),
                ),
                (
                    "is_stored_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Đã lưu blockchain"
                    ),
                ),
                (
                    "blockchain_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tải lên",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xác thực",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="administrative.document",
                        verbose_name="Giấy tờ",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="administrative.request",
                        verbose_name="Yêu cầu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài liệu đính kèm",
                "verbose_name_plural": "Tài liệu đính kèm",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã phê duyệt",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("approved", "Đã phê duyệt"),
                            ("rejected", "Từ chối"),
                            ("revoked", "Thu hồi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Mức độ ưu tiên"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "approval_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do phê duyệt"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do từ chối"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian yêu cầu"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Thời hạn phê duyệt"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian phê duyệt"
                    ),
                ),
                (
                    "blockchain_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                (
                    "is_recorded_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Đã ghi blockchain"
                    ),
                ),
                (
                    "digital_signature",
                    models.TextField(
                        blank=True, null=True, verbose_name="Chữ ký điện tử"
                    ),
                ),
                (
                    "signature_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian ký"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phê duyệt",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người yêu cầu phê duyệt",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="administrative.document",
                        verbose_name="Giấy tờ",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="administrative.request",
                        verbose_name="Yêu cầu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phê duyệt",
                "verbose_name_plural": "Phê duyệt",
                "ordering": ["-requested_at", "status", "priority"],
            },
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["request_id"], name="administrat_request_faf791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["reference_number"], name="administrat_referen_078b50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["requestor"], name="administrat_request_58643f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="administrat_status_9db5da_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["priority"], name="administrat_priorit_50e358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_id"], name="administrat_documen_a3bee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["reference_number"], name="administrat_referen_fdb3cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["issued_to"], name="administrat_issued__7f0f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="administrat_status_edf3e2_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["attachment_id"], name="administrat_attachm_6fd657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["request"], name="administrat_request_fbe4cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["document"], name="administrat_documen_5969af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["attachment_type"], name="administrat_attachm_924ade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["approval_id"], name="administrat_approva_13b88b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["document"], name="administrat_documen_307dfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["request"], name="administrat_request_e52962_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(fields=["status"], name="administrat_status_9671f0_idx"),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["requested_by"], name="administrat_request_6675c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["approver"], name="administrat_approve_b013df_idx"
            ),
        ),
    ]
