# Generated by Django 5.2.1 on 2025-05-17 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0001_initial"),
        ("blockchain", "0002_document_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Đăng nhập"),
                            ("request_created", "Tạo yêu cầu"),
                            ("request_updated", "Cập nhật yêu cầu"),
                            ("request_submitted", "Nộp yêu cầu"),
                            ("request_approved", "Phê duyệt yêu cầu"),
                            ("request_rejected", "Từ chối yêu cầu"),
                            ("document_created", "Tạo giấy tờ"),
                            ("document_updated", "Cập nhật giấy tờ"),
                            ("document_approved", "Phê duyệt giấy tờ"),
                            ("document_issued", "Cấp giấy tờ"),
                            ("document_verified", "Xác minh giấy tờ"),
                            ("notification", "Thông báo"),
                            ("system", "Hoạt động hệ thống"),
                            ("other", "Khác"),
                        ],
                        max_length=30,
                        verbose_name="Loại hoạt động",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Quan trọng"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dữ liệu bổ sung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="blockchain.document",
                        verbose_name="Giấy tờ liên quan",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="blockchain.request",
                        verbose_name="Yêu cầu liên quan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoạt động",
                "verbose_name_plural": "Hoạt động",
                "ordering": ["-created_at"],
            },
        ),
    ]
