# Generated by Django 5.2.1 on 2025-05-17 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên contract")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Phiên bản")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("document", "Quản lý giấy tờ"),
                            ("user", "Quản lý người dùng"),
                            ("officer", "Quản lý cán bộ"),
                            ("admin", "Quản lý hành chính"),
                            ("verification", "Xác thực"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại contract",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("hyperledger", "Hyperledger Fabric"),
                            ("quorum", "Quorum"),
                        ],
                        max_length=20,
                        verbose_name="Mạng blockchain",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Địa chỉ contract",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Channel"
                    ),
                ),
                (
                    "chaincode_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Chaincode ID",
                    ),
                ),
                ("abi", models.JSONField(blank=True, default=dict, verbose_name="ABI")),
                (
                    "bytecode",
                    models.TextField(blank=True, null=True, verbose_name="Bytecode"),
                ),
                (
                    "source_code",
                    models.TextField(blank=True, null=True, verbose_name="Mã nguồn"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("inactive", "Không hoạt động"),
                            ("deprecated", "Không dùng nữa"),
                            ("testing", "Đang kiểm thử"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "functions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Danh sách hàm"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian triển khai"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chủ sở hữu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Contract",
                "verbose_name_plural": "Smart Contracts",
                "ordering": ["type", "name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã bản ghi",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash giao dịch",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("hyperledger", "Hyperledger Fabric"),
                            ("quorum", "Quorum"),
                        ],
                        default="hyperledger",
                        max_length=20,
                        verbose_name="Mạng blockchain",
                    ),
                ),
                (
                    "block_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số block"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=50, verbose_name="ID đối tượng"),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("document_creation", "Tạo giấy tờ"),
                            ("document_update", "Cập nhật giấy tờ"),
                            ("document_revocation", "Thu hồi giấy tờ"),
                            ("officer_approval", "Phê duyệt cán bộ"),
                            ("request_creation", "Tạo yêu cầu"),
                            ("request_update", "Cập nhật yêu cầu"),
                            ("verification", "Xác thực"),
                            ("signature", "Ký số"),
                            ("other", "Khác"),
                        ],
                        max_length=30,
                        verbose_name="Loại bản ghi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("submitted", "Đã gửi"),
                            ("confirmed", "Đã xác nhận"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Dữ liệu"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "verification_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash xác thực",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Đã xác thực"),
                ),
                (
                    "verification_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian xác thực"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian xác nhận"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Thông báo lỗi"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Số lần thử lại"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Loại đối tượng",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockchain_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "smart_contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="blockchain.smartcontract",
                        verbose_name="Smart contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bản ghi blockchain",
                "verbose_name_plural": "Bản ghi blockchain",
                "ordering": ["-created_at", "status"],
            },
        ),
        migrations.AddIndex(
            model_name="smartcontract",
            index=models.Index(fields=["name"], name="blockchain__name_247a03_idx"),
        ),
        migrations.AddIndex(
            model_name="smartcontract",
            index=models.Index(
                fields=["address"], name="blockchain__address_fcf1cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartcontract",
            index=models.Index(fields=["status"], name="blockchain__status_68d107_idx"),
        ),
        migrations.AddIndex(
            model_name="smartcontract",
            index=models.Index(fields=["type"], name="blockchain__type_5eccf1_idx"),
        ),
        migrations.AddIndex(
            model_name="smartcontract",
            index=models.Index(
                fields=["network"], name="blockchain__network_52579b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="smartcontract",
            unique_together={("name", "version", "network")},
        ),
        migrations.AddIndex(
            model_name="blockchainrecord",
            index=models.Index(
                fields=["record_id"], name="blockchain__record__b39786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainrecord",
            index=models.Index(
                fields=["transaction_id"], name="blockchain__transac_bc0216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainrecord",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="blockchain__content_0f25c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainrecord",
            index=models.Index(fields=["status"], name="blockchain__status_467df7_idx"),
        ),
        migrations.AddIndex(
            model_name="blockchainrecord",
            index=models.Index(
                fields=["record_type"], name="blockchain__record__b346b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainrecord",
            index=models.Index(
                fields=["created_by"], name="blockchain__created_0c6bf2_idx"
            ),
        ),
    ]
