# Generated by Django 5.2.1 on 2025-05-17 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Giấy khai sinh"),
                            ("death_certificate", "Giấy chứng tử"),
                            ("marriage_certificate", "Giấy chứng nhận kết hôn"),
                            ("household_registration", "Đăng ký hộ khẩu"),
                            ("temporary_residence", "Đăng ký tạm trú"),
                            ("identification", "Giấy tờ tùy thân"),
                            ("land_use_right", "Giấy chứng nhận quyền sử dụng đất"),
                            ("business_license", "Giấy phép kinh doanh"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                        verbose_name="Loại giấy tờ",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Số giấy tờ"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Nội dung"),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cơ quan cấp",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày cấp"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Đang chờ"),
                            ("processing", "Đang xử lý"),
                            ("approved", "Đã phê duyệt"),
                            ("rejected", "Từ chối"),
                            ("issued", "Đã cấp"),
                            ("revoked", "Đã thu hồi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Đã xác minh blockchain"
                    ),
                ),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash blockchain",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tệp đính kèm"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phê duyệt",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Công dân",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giấy tờ",
                "verbose_name_plural": "Giấy tờ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("document_issuance", "Cấp giấy tờ"),
                            ("document_renewal", "Gia hạn giấy tờ"),
                            ("document_modification", "Sửa đổi giấy tờ"),
                            ("document_cancellation", "Hủy giấy tờ"),
                            ("information_request", "Yêu cầu thông tin"),
                            ("blockchain_verification", "Xác minh blockchain"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                        verbose_name="Loại yêu cầu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("submitted", "Đã gửi"),
                            ("pending", "Đang chờ"),
                            ("processing", "Đang xử lý"),
                            ("additional_info_requested", "Yêu cầu bổ sung thông tin"),
                            ("completed", "Hoàn thành"),
                            ("approved", "Đã phê duyệt"),
                            ("rejected", "Từ chối"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("normal", "Bình thường"),
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                            ("urgent", "Khẩn cấp"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Mức ưu tiên",
                    ),
                ),
                (
                    "needs_chairman_approval",
                    models.BooleanField(
                        default=False, verbose_name="Cần phê duyệt của chủ tịch"
                    ),
                ),
                (
                    "is_visible_to_citizen",
                    models.BooleanField(
                        default=True, verbose_name="Hiển thị cho công dân"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do từ chối"
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú bổ sung"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tệp đính kèm"
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dữ liệu biểu mẫu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày nộp"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày xử lý"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Công dân",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_requests",
                        to="blockchain.document",
                        verbose_name="Giấy tờ liên quan",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockchain_assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cán bộ xử lý",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu",
                "verbose_name_plural": "Yêu cầu",
                "ordering": ["-created_at"],
            },
        ),
    ]
