# Generated by Django 5.2.1 on 2025-05-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0002_document_request"),
        ("accounts", "0004_alter_user_options_user_address_user_blockchain_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='officer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='blockchain_assigned_requests',
                to='accounts.user',
                verbose_name='Cán bộ xử lý',
            ),
        ),
    ]
