# Generated by Django 5.2.1 on 2025-05-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0003_auto_20250517_2243"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="citizen",
            new_name="issued_to",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="citizen",
            new_name="requestor",
        ),
    ]
