# Generated by Django 5.2.1 on 2025-05-16 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã yêu cầu",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số tham chiếu"
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("general_admin", "Cán bộ hành chính chung"),
                            ("land_admin", "Cán bộ địa chính"),
                            ("civil_status", "Cán bộ hộ tịch"),
                            ("cultural_social", "Cán bộ văn hóa - xã hội"),
                            ("military", "Cán bộ quân sự"),
                            ("financial", "Cán bộ tài chính"),
                            ("justice", "Cán bộ tư pháp"),
                            ("other", "Chức vụ khác"),
                        ],
                        max_length=30,
                        verbose_name="Vai trò yêu cầu",
                    ),
                ),
                (
                    "role_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả vai trò"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, null=True, verbose_name="Trình độ học vấn"
                    ),
                ),
                (
                    "experience",
                    models.TextField(blank=True, null=True, verbose_name="Kinh nghiệm"),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Bằng cấp/Chứng chỉ"
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do ứng tuyển"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ xét duyệt"),
                            ("reviewing", "Đang xem xét"),
                            ("additional_info_required", "Yêu cầu bổ sung thông tin"),
                            ("approved", "Đã phê duyệt"),
                            ("rejected", "Từ chối"),
                            ("revoked", "Thu hồi"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do từ chối"
                    ),
                ),
                (
                    "additional_info_request",
                    models.TextField(
                        blank=True, null=True, verbose_name="Yêu cầu bổ sung thông tin"
                    ),
                ),
                (
                    "additional_info_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phản hồi bổ sung"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày nộp"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày phê duyệt"
                    ),
                ),
                (
                    "rejected_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày từ chối"
                    ),
                ),
                (
                    "is_recorded_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Đã ghi blockchain"
                    ),
                ),
                (
                    "blockchain_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_officer_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phê duyệt",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_officer_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xem xét",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officer_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người yêu cầu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu đăng ký cán bộ",
                "verbose_name_plural": "Yêu cầu đăng ký cán bộ",
                "ordering": ["-submitted_date", "status"],
            },
        ),
        migrations.CreateModel(
            name="OfficerApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã phê duyệt",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("approved", "Đã phê duyệt"),
                            ("rejected", "Từ chối"),
                            ("revoked", "Thu hồi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "approval_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do phê duyệt"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do từ chối"
                    ),
                ),
                (
                    "assigned_duties",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nhiệm vụ được giao"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày bắt đầu"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                (
                    "probation_period",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Thời gian thử việc (tháng)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày phê duyệt"
                    ),
                ),
                (
                    "is_recorded_blockchain",
                    models.BooleanField(
                        default=False, verbose_name="Đã ghi blockchain"
                    ),
                ),
                (
                    "blockchain_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID giao dịch blockchain",
                    ),
                ),
                (
                    "digital_signature",
                    models.TextField(
                        blank=True, null=True, verbose_name="Chữ ký điện tử"
                    ),
                ),
                (
                    "signature_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian ký"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officer_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phê duyệt",
                    ),
                ),
                (
                    "officer_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to="officer_management.officerrequest",
                        verbose_name="Yêu cầu cán bộ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phê duyệt cán bộ",
                "verbose_name_plural": "Phê duyệt cán bộ",
                "ordering": ["-created_at", "status"],
            },
        ),
        migrations.CreateModel(
            name="OfficerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã nhiệm vụ",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tiêu đề nhiệm vụ"),
                ),
                ("description", models.TextField(verbose_name="Mô tả nhiệm vụ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Đã phân công"),
                            ("in_progress", "Đang thực hiện"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                            ("overdue", "Quá hạn"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("normal", "Bình thường"),
                            ("high", "Cao"),
                            ("urgent", "Khẩn cấp"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Mức độ ưu tiên",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày giao"),
                ),
                ("due_date", models.DateTimeField(verbose_name="Thời hạn")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày bắt đầu"
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày hoàn thành"
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tiến độ (%)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "completion_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú hoàn thành"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người giao nhiệm vụ",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cán bộ được giao",
                    ),
                ),
                (
                    "parent_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="officer_management.officerassignment",
                        verbose_name="Nhiệm vụ cha",
                    ),
                ),
                (
                    "related_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officer_assignments",
                        to="administrative.request",
                        verbose_name="Yêu cầu liên quan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhiệm vụ cán bộ",
                "verbose_name_plural": "Nhiệm vụ cán bộ",
                "ordering": ["-assigned_date", "priority", "status"],
                "indexes": [
                    models.Index(
                        fields=["assignment_id"], name="officer_man_assignm_1a6a7c_idx"
                    ),
                    models.Index(
                        fields=["officer"], name="officer_man_officer_df4307_idx"
                    ),
                    models.Index(
                        fields=["status"], name="officer_man_status_41337b_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="officer_man_priorit_2cd04c_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="officer_man_due_dat_633e2a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="officerrequest",
            index=models.Index(
                fields=["request_id"], name="officer_man_request_2cd8cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officerrequest",
            index=models.Index(
                fields=["reference_number"], name="officer_man_referen_b1fded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officerrequest",
            index=models.Index(fields=["user"], name="officer_man_user_id_80cf06_idx"),
        ),
        migrations.AddIndex(
            model_name="officerrequest",
            index=models.Index(fields=["status"], name="officer_man_status_293680_idx"),
        ),
        migrations.AddIndex(
            model_name="officerrequest",
            index=models.Index(
                fields=["requested_role"], name="officer_man_request_721b99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officerapproval",
            index=models.Index(
                fields=["approval_id"], name="officer_man_approva_d1b64c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officerapproval",
            index=models.Index(
                fields=["officer_request"], name="officer_man_officer_25f920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officerapproval",
            index=models.Index(
                fields=["approver"], name="officer_man_approve_ac7777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officerapproval",
            index=models.Index(fields=["status"], name="officer_man_status_aa01a2_idx"),
        ),
    ]
