// Vietnamese administrative regions data
export const provinces = [
  { id: 1, name: "Hà Nội" },
  { id: 2, name: "Hồ Chí Minh" },
  { id: 3, name: "Đà Nẵng" },
  { id: 4, name: "Hải Phòng" },
  { id: 5, name: "Cần Thơ" },
  { id: 6, name: "An Giang" },
  { id: 7, name: "Bà Rịa - Vũng Tàu" },
  { id: 8, name: "Bắc Giang" },
  { id: 9, name: "Bắc Kạn" },
  { id: 10, name: "Bạc Liêu" },
  { id: 11, name: "Bắc Ninh" },
  { id: 12, name: "Bến Tre" },
  { id: 13, name: "Bình Định" },
  { id: 14, name: "Bình Dương" },
  { id: 15, name: "Bình Phước" },
  { id: 16, name: "Bình Thuận" },
  { id: 17, name: "Cà Mau" },
  { id: 18, name: "Cao Bằng" },
  { id: 19, name: "Đắk Lắk" },
  { id: 20, name: "Đắk Nông" },
  { id: 21, name: "Điện Biên" },
  { id: 22, name: "Đồng Nai" },
  { id: 23, name: "Đồng Tháp" },
  { id: 24, name: "Gia Lai" },
  { id: 25, name: "Hà Giang" },
  { id: 26, name: "Hà Nam" },
  { id: 27, name: "Hà Tĩnh" },
  { id: 28, name: "Hải Dương" },
  { id: 29, name: "Hậu Giang" },
  { id: 30, name: "Hòa Bình" },
  { id: 31, name: "Hưng Yên" },
  { id: 32, name: "Khánh Hòa" },
  { id: 33, name: "Kiên Giang" },
  { id: 34, name: "Kon Tum" },
  { id: 35, name: "Lai Châu" },
  { id: 36, name: "Lâm Đồng" },
  { id: 37, name: "Lạng Sơn" },
  { id: 38, name: "Lào Cai" },
  { id: 39, name: "Long An" },
  { id: 40, name: "Nam Định" },
  { id: 41, name: "Nghệ An" },
  { id: 42, name: "Ninh Bình" },
  { id: 43, name: "Ninh Thuận" },
  { id: 44, name: "Phú Thọ" },
  { id: 45, name: "Phú Yên" },
  { id: 46, name: "Quảng Bình" },
  { id: 47, name: "Quảng Nam" },
  { id: 48, name: "Quảng Ngãi" },
  { id: 49, name: "Quảng Ninh" },
  { id: 50, name: "Quảng Trị" },
  { id: 51, name: "Sóc Trăng" },
  { id: 52, name: "Sơn La" },
  { id: 53, name: "Tây Ninh" },
  { id: 54, name: "Thái Bình" },
  { id: 55, name: "Thái Nguyên" },
  { id: 56, name: "Thanh Hóa" },
  { id: 57, name: "Thừa Thiên Huế" },
  { id: 58, name: "Tiền Giang" },
  { id: 59, name: "Trà Vinh" },
  { id: 60, name: "Tuyên Quang" },
  { id: 61, name: "Vĩnh Long" },
  { id: 62, name: "Vĩnh Phúc" },
  { id: 63, name: "Yên Bái" }
];

// Districts by province
export const districts = {
  1: [ // Hà Nội
    { id: 1, name: "Ba Đình" },
    { id: 2, name: "Hoàn Kiếm" },
    { id: 3, name: "Tây Hồ" },
    { id: 4, name: "Long Biên" },
    { id: 5, name: "Cầu Giấy" },
    { id: 6, name: "Đống Đa" },
    { id: 7, name: "Hai Bà Trưng" },
    { id: 8, name: "Hoàng Mai" },
    { id: 9, name: "Thanh Xuân" },
    { id: 10, name: "Sóc Sơn" },
    { id: 11, name: "Đông Anh" },
    { id: 12, name: "Gia Lâm" },
    { id: 13, name: "Nam Từ Liêm" },
    { id: 14, name: "Thanh Trì" },
    { id: 15, name: "Bắc Từ Liêm" },
    { id: 16, name: "Mê Linh" },
    { id: 17, name: "Hà Đông" },
    { id: 18, name: "Sơn Tây" },
    { id: 19, name: "Ba Vì" },
    { id: 20, name: "Chương Mỹ" },
    { id: 21, name: "Đan Phượng" },
    { id: 22, name: "Hoài Đức" },
    { id: 23, name: "Mỹ Đức" },
    { id: 24, name: "Phú Xuyên" },
    { id: 25, name: "Phúc Thọ" },
    { id: 26, name: "Quốc Oai" },
    { id: 27, name: "Thạch Thất" },
    { id: 28, name: "Thanh Oai" },
    { id: 29, name: "Thường Tín" },
    { id: 30, name: "Ứng Hòa" }
  ],
  2: [ // Hồ Chí Minh
    { id: 1, name: "Quận 1" },
    { id: 2, name: "Quận 3" },
    { id: 3, name: "Quận 4" },
    { id: 4, name: "Quận 5" },
    { id: 5, name: "Quận 6" },
    { id: 6, name: "Quận 7" },
    { id: 7, name: "Quận 8" },
    { id: 8, name: "Quận 10" },
    { id: 9, name: "Quận 11" },
    { id: 10, name: "Quận 12" },
    { id: 11, name: "Thủ Đức" },
    { id: 12, name: "Gò Vấp" },
    { id: 13, name: "Bình Thạnh" },
    { id: 14, name: "Tân Bình" },
    { id: 15, name: "Tân Phú" },
    { id: 16, name: "Phú Nhuận" },
    { id: 17, name: "Bình Tân" },
    { id: 18, name: "Củ Chi" },
    { id: 19, name: "Hóc Môn" },
    { id: 20, name: "Bình Chánh" },
    { id: 21, name: "Nhà Bè" },
    { id: 22, name: "Cần Giờ" }
  ],
  3: [ // Đà Nẵng
    { id: 1, name: "Hải Châu" },
    { id: 2, name: "Thanh Khê" },
    { id: 3, name: "Sơn Trà" },
    { id: 4, name: "Ngũ Hành Sơn" },
    { id: 5, name: "Liên Chiểu" },
    { id: 6, name: "Cẩm Lệ" },
    { id: 7, name: "Hòa Vang" }
  ],
  4: [ // Hải Phòng
    { id: 1, name: "Hồng Bàng" },
    { id: 2, name: "Lê Chân" },
    { id: 3, name: "Ngô Quyền" },
    { id: 4, name: "Kiến An" },
    { id: 5, name: "Hải An" },
    { id: 6, name: "Đồ Sơn" },
    { id: 7, name: "Dương Kinh" },
    { id: 8, name: "Thủy Nguyên" },
    { id: 9, name: "An Dương" },
    { id: 10, name: "An Lão" },
    { id: 11, name: "Kiến Thụy" },
    { id: 12, name: "Tiên Lãng" },
    { id: 13, name: "Vĩnh Bảo" },
    { id: 14, name: "Cát Hải" },
    { id: 15, name: "Bạch Long Vĩ" }
  ],
  5: [ // Cần Thơ
    { id: 1, name: "Ninh Kiều" },
    { id: 2, name: "Ô Môn" },
    { id: 3, name: "Bình Thủy" },
    { id: 4, name: "Cái Răng" },
    { id: 5, name: "Thốt Nốt" },
    { id: 6, name: "Vĩnh Thạnh" },
    { id: 7, name: "Cờ Đỏ" },
    { id: 8, name: "Phong Điền" },
    { id: 9, name: "Thới Lai" }
  ],
  7: [ // Bà Rịa - Vũng Tàu
    { id: 1, name: "Vũng Tàu" },
    { id: 2, name: "Bà Rịa" },
    { id: 3, name: "Châu Đức" },
    { id: 4, name: "Côn Đảo" },
    { id: 5, name: "Đất Đỏ" },
    { id: 6, name: "Long Điền" },
    { id: 7, name: "Tân Thành" },
    { id: 8, name: "Xuyên Mộc" }
  ],
  14: [ // Bình Dương
    { id: 1, name: "Thủ Dầu Một" },
    { id: 2, name: "Bàu Bàng" },
    { id: 3, name: "Bến Cát" },
    { id: 4, name: "Dầu Tiếng" },
    { id: 5, name: "Dĩ An" },
    { id: 6, name: "Phú Giáo" },
    { id: 7, name: "Tân Uyên" },
    { id: 8, name: "Thuận An" },
    { id: 9, name: "Bắc Tân Uyên" }
  ],
  22: [ // Đồng Nai
    { id: 1, name: "Biên Hòa" },
    { id: 2, name: "Long Khánh" },
    { id: 3, name: "Cẩm Mỹ" },
    { id: 4, name: "Định Quán" },
    { id: 5, name: "Long Thành" },
    { id: 6, name: "Nhơn Trạch" },
    { id: 7, name: "Tân Phú" },
    { id: 8, name: "Thống Nhất" },
    { id: 9, name: "Trảng Bom" },
    { id: 10, name: "Vĩnh Cửu" },
    { id: 11, name: "Xuân Lộc" }
  ],
  32: [ // Khánh Hòa
    { id: 1, name: "Nha Trang" },
    { id: 2, name: "Cam Ranh" },
    { id: 3, name: "Ninh Hòa" },
    { id: 4, name: "Cam Lâm" },
    { id: 5, name: "Khánh Sơn" },
    { id: 6, name: "Khánh Vĩnh" },
    { id: 7, name: "Trường Sa" },
    { id: 8, name: "Vạn Ninh" }
  ]
};

// Wards by district (format: "provinceId-districtId")
export const wards = {
  // Hà Nội - Ba Đình
  "1-1": [
    { id: 1, name: "Phúc Xá" },
    { id: 2, name: "Trúc Bạch" },
    { id: 3, name: "Vĩnh Phúc" },
    { id: 4, name: "Cống Vị" },
    { id: 5, name: "Liễu Giai" },
    { id: 6, name: "Nguyễn Trung Trực" },
    { id: 7, name: "Quán Thánh" },
    { id: 8, name: "Thành Công" },
    { id: 9, name: "Giảng Võ" },
    { id: 10, name: "Kim Mã" },
    { id: 11, name: "Ngọc Khánh" },
    { id: 12, name: "Ngọc Hà" },
    { id: 13, name: "Điện Biên" },
    { id: 14, name: "Đội Cấn" }
  ],
  // Hà Nội - Hoàn Kiếm
  "1-2": [
    { id: 1, name: "Chương Dương" },
    { id: 2, name: "Cửa Đông" },
    { id: 3, name: "Cửa Nam" },
    { id: 4, name: "Đồng Xuân" },
    { id: 5, name: "Hàng Bạc" },
    { id: 6, name: "Hàng Bài" },
    { id: 7, name: "Hàng Bồ" },
    { id: 8, name: "Hàng Bông" },
    { id: 9, name: "Hàng Buồm" },
    { id: 10, name: "Hàng Đào" },
    { id: 11, name: "Hàng Gai" },
    { id: 12, name: "Hàng Mã" },
    { id: 13, name: "Hàng Trống" },
    { id: 14, name: "Lý Thái Tổ" },
    { id: 15, name: "Phan Chu Trinh" },
    { id: 16, name: "Phúc Tân" },
    { id: 17, name: "Trần Hưng Đạo" },
    { id: 18, name: "Tràng Tiền" }
  ],
  // Hồ Chí Minh - Quận 1
  "2-1": [
    { id: 1, name: "Bến Nghé" },
    { id: 2, name: "Bến Thành" },
    { id: 3, name: "Cầu Kho" },
    { id: 4, name: "Cầu Ông Lãnh" },
    { id: 5, name: "Cô Giang" },
    { id: 6, name: "Đa Kao" },
    { id: 7, name: "Nguyễn Cư Trinh" },
    { id: 8, name: "Nguyễn Thái Bình" },
    { id: 9, name: "Phạm Ngũ Lão" },
    { id: 10, name: "Tân Định" }
  ],
  // Hồ Chí Minh - Thủ Đức
  "2-11": [
    { id: 1, name: "Bình Chiểu" },
    { id: 2, name: "Bình Thọ" },
    { id: 3, name: "Hiệp Bình Chánh" },
    { id: 4, name: "Hiệp Bình Phước" },
    { id: 5, name: "Linh Chiểu" },
    { id: 6, name: "Linh Đông" },
    { id: 7, name: "Linh Tây" },
    { id: 8, name: "Linh Trung" },
    { id: 9, name: "Linh Xuân" },
    { id: 10, name: "Tam Bình" },
    { id: 11, name: "Tam Phú" },
    { id: 12, name: "Trường Thọ" }
  ],
  // Đà Nẵng - Hải Châu
  "3-1": [
    { id: 1, name: "Bình Hiên" },
    { id: 2, name: "Bình Thuận" },
    { id: 3, name: "Hải Châu I" },
    { id: 4, name: "Hải Châu II" },
    { id: 5, name: "Hòa Cường Bắc" },
    { id: 6, name: "Hòa Cường Nam" },
    { id: 7, name: "Hòa Thuận Đông" },
    { id: 8, name: "Hòa Thuận Tây" },
    { id: 9, name: "Nam Dương" },
    { id: 10, name: "Phước Ninh" },
    { id: 11, name: "Thạch Thang" },
    { id: 12, name: "Thanh Bình" },
    { id: 13, name: "Thuận Phước" }
  ],
  // Bà Rịa - Vũng Tàu - Vũng Tàu
  "7-1": [
    { id: 1, name: "Phường 1" },
    { id: 2, name: "Phường 2" },
    { id: 3, name: "Phường 3" },
    { id: 4, name: "Phường 4" },
    { id: 5, name: "Phường 5" },
    { id: 6, name: "Phường 6" },
    { id: 7, name: "Phường 7" },
    { id: 8, name: "Phường 8" },
    { id: 9, name: "Phường 9" },
    { id: 10, name: "Phường 10" },
    { id: 11, name: "Phường 11" },
    { id: 12, name: "Phường 12" },
    { id: 13, name: "Rạch Dừa" },
    { id: 14, name: "Thắng Nhất" },
    { id: 15, name: "Thắng Nhì" },
    { id: 16, name: "Thắng Tam" }
  ],
  // Bà Rịa - Vũng Tàu - Bà Rịa
  "7-2": [
    { id: 1, name: "Long Hương" },
    { id: 2, name: "Long Tâm" },
    { id: 3, name: "Long Toàn" },
    { id: 4, name: "Phước Hiệp" },
    { id: 5, name: "Phước Hưng" },
    { id: 6, name: "Phước Nguyên" },
    { id: 7, name: "Phước Trung" },
    { id: 8, name: "Kim Dinh" }
  ],
  // Bình Dương - Thủ Dầu Một
  "14-1": [
    { id: 1, name: "Chánh Mỹ" },
    { id: 2, name: "Chánh Nghĩa" },
    { id: 3, name: "Định Hòa" },
    { id: 4, name: "Hiệp An" },
    { id: 5, name: "Hiệp Thành" },
    { id: 6, name: "Hòa Phú" },
    { id: 7, name: "Phú Cường" },
    { id: 8, name: "Phú Hòa" },
    { id: 9, name: "Phú Lợi" },
    { id: 10, name: "Phú Mỹ" },
    { id: 11, name: "Phú Tân" },
    { id: 12, name: "Phú Thọ" },
    { id: 13, name: "Tân An" },
    { id: 14, name: "Tương Bình Hiệp" }
  ],
  // Đồng Nai - Biên Hòa
  "22-1": [
    { id: 1, name: "An Bình" },
    { id: 2, name: "Bình Đa" },
    { id: 3, name: "Hố Nai" },
    { id: 4, name: "Hòa Bình" },
    { id: 5, name: "Long Bình" },
    { id: 6, name: "Long Bình Tân" },
    { id: 7, name: "Phước Tân" },
    { id: 8, name: "Quang Vinh" },
    { id: 9, name: "Quyết Thắng" },
    { id: 10, name: "Tam Hiệp" },
    { id: 11, name: "Tam Hòa" },
    { id: 12, name: "Tân Biên" },
    { id: 13, name: "Tân Hiệp" },
    { id: 14, name: "Tân Hòa" },
    { id: 15, name: "Tân Mai" },
    { id: 16, name: "Tân Phong" },
    { id: 17, name: "Tân Tiến" },
    { id: 18, name: "Tân Vạn" },
    { id: 19, name: "Thanh Bình" },
    { id: 20, name: "Thống Nhất" },
    { id: 21, name: "Trảng Dài" },
    { id: 22, name: "Trung Dũng" },
    { id: 23, name: "Bửu Hòa" },
    { id: 24, name: "Bửu Long" },
    { id: 25, name: "Tân Hiệp" },
    { id: 26, name: "Tân Hòa" },
    { id: 27, name: "Hiệp Hòa" },
    { id: 28, name: "Hóa An" },
    { id: 29, name: "Tân Vạn" },
    { id: 30, name: "Bình Đa" }
  ],
  // Khánh Hòa - Nha Trang
  "32-1": [
    { id: 1, name: "Lộc Thọ" },
    { id: 2, name: "Ngọc Hiệp" },
    { id: 3, name: "Phước Hải" },
    { id: 4, name: "Phước Hòa" },
    { id: 5, name: "Phước Long" },
    { id: 6, name: "Phước Tân" },
    { id: 7, name: "Phước Tiến" },
    { id: 8, name: "Phương Sài" },
    { id: 9, name: "Phương Sơn" },
    { id: 10, name: "Tân Lập" },
    { id: 11, name: "Vạn Thạnh" },
    { id: 12, name: "Vạn Thắng" },
    { id: 13, name: "Vĩnh Hải" },
    { id: 14, name: "Vĩnh Hòa" },
    { id: 15, name: "Vĩnh Nguyên" },
    { id: 16, name: "Vĩnh Phước" },
    { id: 17, name: "Vĩnh Thọ" },
    { id: 18, name: "Vĩnh Trường" },
    { id: 19, name: "Xương Huân" }
  ]
};

// For other provinces/districts, we'll show a default list of generic wards
export const defaultWards = [
  { id: 1, name: "Phường/Xã 1" },
  { id: 2, name: "Phường/Xã 2" },
  { id: 3, name: "Phường/Xã 3" },
  { id: 4, name: "Phường/Xã 4" },
  { id: 5, name: "Phường/Xã 5" }
];

// For other provinces, we'll show a default list of generic districts
export const defaultDistricts = [
  { id: 1, name: "Quận/Huyện 1" },
  { id: 2, name: "Quận/Huyện 2" },
  { id: 3, name: "Quận/Huyện 3" },
  { id: 4, name: "Quận/Huyện 4" },
  { id: 5, name: "Quận/Huyện 5" }
];

// Helper function to get districts by province ID
export const getDistrictsByProvinceId = (provinceId) => {
  return districts[provinceId] || defaultDistricts;
};

// Helper function to get wards by province ID and district ID
export const getWardsByDistrictId = (provinceId, districtId) => {
  const key = `${provinceId}-${districtId}`;
  return wards[key] || defaultWards;
}; 