# Generated by Django 5.2.1 on 2025-05-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blockchain_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("citizen", "Công dân"),
                    ("officer", "Cán bộ"),
                    ("chairman", "Chủ tịch"),
                ],
                default="citizen",
                max_length=20,
            ),
        ),
    ]
