# Generated by Django 5.2.1 on 2025-05-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_user_options_user_address_user_blockchain_id_and_more",
        ),
    ]

    operations = []
