# Generated by Django 5.2.1 on 2025-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("chairman", "Chairman"),
                    ("officer", "Officer"),
                    ("citizen", "Citizen"),
                    ("officer_pending", "Officer Pending"),
                ],
                default="citizen",
                max_length=20,
                unique=True,
            ),
        ),
    ]
