# Generated by Django 5.2.1 on 2025-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blockchain_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_REGISTERED", "Not Registered"),
                    ("REGISTERED", "Registered"),
                    ("UPDATED", "Updated"),
                    ("ERROR", "Error"),
                ],
                default="NOT_REGISTERED",
                max_length=20,
                null=True,
                verbose_name="Blockchain Status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blockchain_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Blockchain Timestamp"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blockchain_tx_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Blockchain Transaction ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="identification_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Identification Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("citizen", "Citizen"),
                    ("officer", "Officer"),
                    ("chairman", "Chairman"),
                    ("admin", "Admin"),
                ],
                default="citizen",
                max_length=10,
                verbose_name="User Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="blockchain_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Blockchain ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Citizen"),
                    ("OFFICER", "Officer"),
                    ("CHAIRMAN", "Chairman"),
                    ("ADMIN", "Admin"),
                ],
                default="CITIZEN",
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
